access_token: "6baca547742c6f96a6ff71b138424f21"
server_name: "test"  # Bridge API server name (use 'test' for test data)

# Search parameters (Note: API filtering not supported, done client-side)
zip_codes: ["37415", "37405", "37409"]  # Chattanooga, TN area
min_price: 150000
max_price: 300000
min_beds: 2
min_baths: 1
propertyType: "Single Family"  # Bridge API uses PropertySubType
sort_by: "newest"

