api_key: "1c1c20660cmshb9de78075042139p1d134cjsn83640c308aec"
host: "zillow-com1.p.rapidapi.com"

# Search parameters
zip_codes: ["37415", "37405", "37409"]  # Chattanooga, TN area
min_price: 150000
max_price: 300000
min_beds: 2
min_baths: 1
property_types: ["SINGLE_FAMILY"]
sort_by: "newest"
