api_key: "1c1c20660cmshb9de78075042139p1d134cjsn83640c308aec"
conn: http.client.HTTPSConnection("zillow-com1.p.rapidapi.com")
host: "zillow-com1.p.rapidapi.com"
zip_codes: ["37415", "37405", "37409"]
min_price: 150000
max_price: 300000
min_beds: 2
min_baths: 1
property_types: ["house"]
sort_by: "newest"